/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lianxi1;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author 19852
 */
public class NewJPanel extends javax.swing.JPanel {

    Snake snake;

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(Snake snake) {
        initComponents();
        this.snake = snake;
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        drawSnake(g);
        drawFood(g);
    }

    public void drawSnake(Graphics g) {
        g.setColor(Color.green);
        g.fill3DRect(snake.headCoordinate[0], snake.headCoordinate[1], 20, 20, true);
        g.setColor(Color.gray);
        for (int i = 1; i < snake.length; i++) {
            g.fill3DRect(snake.coordinate.get(i)[0], snake.coordinate.get(i)[1], 20, 20, true);

        }
    }

    public void drawFood(Graphics g) {
        g.setColor(Color.red);
        g.fill3DRect(snake.foodCoordinate[0], snake.foodCoordinate[1], 20, 20, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
